// Draws the seal ribbon's words as outlines, so they scale with the ribbon as one shape.
//
//   node apps/web/scripts/seal-words.mjs
//
// Writes apps/web/src/components/seal-words.ts. Run it again whenever the words, their size or
// their width change. Live text on the ribbon jumped against it as the hover settled (Ethan):
// Chrome redraws a grown layer at its new size and rounds text to whole pixels there, while a
// shape is never rounded. The words are Inter at 600, the ribbon's own face, spaced to fill
// their width as SVG's textLength did (lengthAdjust="spacing").
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import * as fontkit from "fontkit";
import { decompress } from "wawoff2";

const ROOT = path.resolve(import.meta.dirname, "../../..");
const FONT = path.join(
  ROOT,
  "apps/web/node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2",
);
const OUT = path.join(ROOT, "apps/web/src/components/seal-words.ts");

// The ribbon's words as design-tooling-seal.tsx sets them.
const WORDS = "NOW WITH DESIGN TOOLING!";
const SIZE = 11; // px
const WEIGHT = 600;
const WIDTH = 186; // px the words fill, first letter to last advance

// A number to two places, without a trailing zero or a negative zero.
const short = (n) => {
  const fixed = Number(n.toFixed(2));
  return String(Object.is(fixed, -0) ? 0 : fixed);
};

// The font at the ribbon's weight; fontkit varies a TrueType file, not the WOFF2 it ships in.
const ttf = await decompress(readFileSync(FONT)); // → Uint8Array
const font = fontkit.create(Buffer.from(ttf)).getVariation({ wght: WEIGHT });
const scale = SIZE / font.unitsPerEm;
const run = font.layout(WORDS); // → glyphs and their advances, kerned
const natural = run.positions.reduce((sum, each) => sum + each.xAdvance * scale, 0);
const extra = (WIDTH - natural) / (run.glyphs.length - 1); // → px added between letters

// Each glyph's outline at its place, baseline at y = 0, the run starting at x = 0.
let x = 0;
const outlines = run.glyphs.map((glyph, i) => {
  const outline = glyph.path
    .scale(scale, -scale)
    .translate(x + run.positions[i].xOffset * scale, 0)
    .toSVG();
  x += run.positions[i].xAdvance * scale + extra;
  return outline;
});
const d = outlines.join("").replaceAll(/-?\d+\.?\d*(e-?\d+)?/g, (n) => short(Number(n)));

writeFileSync(
  OUT,
  `// Generated by apps/web/scripts/seal-words.mjs; do not edit. Run it again to change the words.

/** The seal ribbon's words, ${JSON.stringify(WORDS)}, as Inter ${WEIGHT} outlines at ${SIZE}px. */
export const SEAL_WORDS = {
  text: ${JSON.stringify(WORDS)},
  /** The outlines, the baseline at y = 0 and the first letter at x = 0. */
  path: ${JSON.stringify(d)},
  /** The width they fill, in px. */
  width: ${WIDTH},
};
`,
);
process.stdout.write(
  `${WORDS}: ${run.glyphs.length} glyphs, ${short(natural)}px set, ${short(extra)}px added between letters, ${d.length} chars of path\n`,
);
